# Shared settings for all presets defined below
[*]
# ngl = 99                     # gpu layers
ctx-size = 12288        
batch-size = 1024            
ubatch-size = 256            
cache-type-k = q8_0          
cache-type-v = q8_0          
flash-attn = true            
reasoning-preserve = false   


[qwen3]
model = /models/Qwen3.5-9B-The-Defiant-Fable-Uncnr-Heretic-NEO-MAX-Q4_K_M.gguf
alias = qwen3

[ornith]
model = /models/Ornith-1.5-9B-Q4_K_M.gguf
alias = ornith

[gemma4]
model = /models/gemma-4-12b-it-UD-IQ3_XXS.gguf
alias = gemma4


