services:
  steam-headless:
    hostname: steam-headless
    image: josh5/steam-headless:debian
    ipc: host
    network_mode: host
    platform: linux/amd64
    privileged: true
    restart: unless-stopped
    runtime: nvidia
    security_opt:
      - apparmor=unconfined
      - seccomp=unconfined
    shm_size: 2048M
    stdin_open: false
    tty: false
    cap_add:
      - AUDIT_WRITE
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - FSETID
      - KILL
      - MKNOD
      - NET_ADMIN
      - SETGID
      - SETUID
      - SYS_ADMIN
      - SYS_NICE
      - SYS_RESOURCE
    cap_drop:
      - ALL
    ulimits:
      nofile:
        soft: 1024
        hard: 524288
    deploy:
      resources:
        limits:
          cpus: "8"
          memory: 12288M
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
                - video
                - utility
    environment:
      # Explanations are all in the .env file
      DISPLAY: ${DISPLAY}
      TZ: ${TZ}
      UID: ${UID}
      UMASK: ${UMASK}
      UMASK_SET: ${UMASK_SET}
      USER_ID: ${USER_ID}
      USER_PASSWORD: ${USER_PASSWORD}
      WEB_UI_MODE: ${WEB_UI_MODE}
      ENABLE_EVDEV_INPUTS: ${ENABLE_EVDEV_INPUTS}
      ENABLE_VNC_AUDIO: ${ENABLE_VNC_AUDIO}
      ENABLE_STEAM: ${ENABLE_STEAM}
      FORCE_X11_DUMMY_CONFIG: ${FORCE_X11_DUMMY_CONFIG}
      GID: ${GID}
      GROUP_ID: ${GROUP_ID}
      HOST_DBUS: ${HOST_DBUS}
      MODE: ${MODE}
      #! REMOVED THESE to change to newer deploy.resources.reservations
      NVIDIA_DRIVER_CAPABILITIES: ${NVIDIA_DRIVER_CAPABILITIES}
      NVIDIA_VISIBLE_DEVICES: ${NVIDIA_VISIBLE_DEVICES}
      PGID: ${PGID}
      PORT_NOVNC_WEB: ${PORT_NOVNC_WEB}
      PUID: ${PUID}
      STEAM_ARGS: ${STEAM_ARGS}
      ENABLE_SUNSHINE: ${ENABLE_SUNSHINE}
      SUNSHINE_PASS: ${SUNSHINE_PASS}
      SUNSHINE_USER: ${SUNSHINE_USER}
    extra_hosts:
      steam-headless: 127.0.0.1
    devices:
      - /dev/uinput:/dev/uinput
      - /dev/dri:/dev/dri
    group_add:
      - 44
      - 107
      - 568
      - 1000
    healthcheck:
      interval: 30s
      retries: 5
      start_interval: 2s
      start_period: 15s
      test:
        - CMD
        - curl
        - --request
        - GET
        - --silent
        - --output
        - /dev/null
        - --show-error
        - --fail
        - http://127.0.0.1:${PORT_NOVNC_WEB}/
      timeout: 5s
    volumes:
      - bind:
          create_host_path: false
          propagation: rprivate
        read_only: false
        source: ${STEAM_HEADLESS_DIR}/home
        target: /home/default
        type: bind
      - bind:
          create_host_path: false
          propagation: rprivate
        read_only: false
        source: ${STEAM_HEADLESS_DIR}/steam-games
        target: /mnt/games
        type: bind
      - bind:
          create_host_path: false
          propagation: rprivate
        read_only: false
        source: ${STEAM_HEADLESS_DIR}/x11-socket
        target: /tmp/.X11-unix
        type: bind
      - bind:
          create_host_path: false
          propagation: rprivate
        read_only: false
        source: ${STEAM_HEADLESS_DIR}/pulse-socket
        target: /tmp/pulse
        type: bind
      - bind:
          create_host_path: false
          propagation: rprivate
        read_only: true
        source: /dev/input/
        target: /dev/input/
        type: bind
networks: {}
